baseurl: ""
url: "https://vnbrs.com"
blog:
  title: "Vinicius Brasil"
  description: "My thoughts on software development, programming, tech and product"
  search_path: "vnbrs.com"
  hero_layout: true
  hero_placeholder: "assets/img/generic_hero.jpg"
  excerpts: true
  inline_footnotes: true
  titles_only: false
  font: '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts: 'Rubik:400,400italic,700,700italic'

author:
  fullname: Vinicius Brasil
  rss: true
  mail: vini@hey.com
  github: vnbrs
  # disqus: dactl
  photo: "uploads/me2.jpg"
  photo2x: "uploads/me.jpg"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

permalink: posts/:slug
excerpt_separator: <!–-break-–>
paginate: 5
paginate_path: '/blog/page-:num/'
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag
exclude: ["README.md", "README.html"]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  endings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
  profile: false
  ignore:
  envs: [local]
