baseURL = "https://debugando.org/"
theme = 'hugo-bearblog'
title = "debugando.org"
author = "Vinicius Brasil"
copyright = "Copyright © 2023, debugando.org."
languageCode = "pt-BR"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Programação além dos bits"
  favicon = "favicon.ico"
  images = ["images/share.png"]
  title = "debugando.org"
  hideMadeWithLine = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
