baseURL = "https://debugando.org/"
theme = 'hugo-bearblog'
title = "Debugando.org"
author = "Vinicius Brasil"
copyright = "Copyright © 2023, Debugando.org."
languageCode = "pt-BR"
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Publicação independente sobre engenharia de software que acredita que bom software vai além dos bits."
  favicon = "favicon.ico"
  images = ["images/share.png"]
  title = "Debugando.org"
  hideMadeWithLine = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
